import { useEffect, useMemo, useRef, useState } from "react";
import { supabase, supabaseConfigured } from "./lib/supabase";
import { revenueSplit, AUTHOR_SHARE, PLATFORM_SHARE } from "./lib/revenue";
import { createPreviewPdf, getPdfPageCount, renderPdfPage } from "./lib/pdf";
import type { Book, LibraryEntry, Profile, Role } from "./lib/types";

const DEMO_BOOKS: Book[] = [
  {id:"demo-1",author_id:"demo",title:"The Celestial Cartographer",author_name:"Mira Voss",description:"A lyrical journey through maps, memory, and distant stars.",genre:"Literary Fiction",language:"English",price:249,is_free:false,total_pages:12,preview_pages:3,cover_path:null,manuscript_path:null,preview_path:null,status:"PUBLISHED",copies_sold:128,rating:4.9},
  {id:"demo-2",author_id:"demo",title:"Letters From The Monsoon",author_name:"Arun Dev",description:"Short stories about rain, home, and the people who wait for both.",genre:"Short Stories",language:"English",price:0,is_free:true,total_pages:8,preview_pages:3,cover_path:null,manuscript_path:null,preview_path:null,status:"PUBLISHED",copies_sold:71,rating:4.8},
  {id:"demo-3",author_id:"demo",title:"Midnight Algorithms",author_name:"Nia Rao",description:"A near-future mystery where a programmer finds a pattern hiding in ordinary life.",genre:"Science Fiction",language:"English",price:199,is_free:false,total_pages:10,preview_pages:3,cover_path:null,manuscript_path:null,preview_path:null,status:"PUBLISHED",copies_sold:94,rating:4.7}
];
const COVERS=["https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=700","https://images.unsplash.com/photo-1512820790803-83ca734da794?w=700","https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=700"];
function cover(b:Book,i=0){return b.cover_path&&supabaseConfigured?supabase.storage.from("covers").getPublicUrl(b.cover_path).data.publicUrl:COVERS[i%COVERS.length]}

export function App(){
 const [profile,setProfile]=useState<Profile|null>(null),[books,setBooks]=useState<Book[]>([]),[library,setLibrary]=useState<LibraryEntry[]>([]);
 const [view,setView]=useState("discover"),[selected,setSelected]=useState<Book|null>(null),[reader,setReader]=useState<{book:Book,page:number,preview:boolean}|null>(null);
 const [auth,setAuth]=useState(false),[publish,setPublish]=useState(false),[search,setSearch]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(false);
 async function load(){setLoading(true);if(!supabaseConfigured){setBooks(DEMO_BOOKS);setLoading(false);return}
  const q=await supabase.from("books").select("*").eq("status","PUBLISHED").order("created_at",{ascending:false});if(q.error){setNotice(q.error.message);setBooks(DEMO_BOOKS)}else setBooks(q.data||[]);
  if(profile){const l=await supabase.from("library").select("*,book:books(*)").eq("user_id",profile.id);setLibrary((l.data||[]) as LibraryEntry[])}setLoading(false)}
 async function profileFor(id:string){const q=await supabase.from("profiles").select("*").eq("id",id).single();setProfile(q.data as Profile||null)}
 useEffect(()=>{load()},[profile]);useEffect(()=>{if(!supabaseConfigured)return;supabase.auth.getSession().then(x=>{if(x.data.session)profileFor(x.data.session.user.id)});const x=supabase.auth.onAuthStateChange((_e,s)=>{if(s)profileFor(s.user.id);else setProfile(null)});return()=>x.data.subscription.unsubscribe()},[]);
 const filtered=useMemo(()=>books.filter(b=>(b.title+" "+b.author_name+" "+b.genre).toLowerCase().includes(search.toLowerCase())),[books,search]);
 async function buy(b:Book){if(!profile){setAuth(true);return}if(b.is_free){await addLibrary(b);return}const s=revenueSplit(b.price);if(window.confirm("Fair Checkout\\n\\nPrice ₹"+b.price.toFixed(2)+"\\nAuthor: ₹"+s.author.toFixed(2)+" (70%)\\nBookSphere: ₹"+s.platform.toFixed(2)+" (30%)\\n\\nConfirm purchase?")){const order=await supabase.from("orders").insert({reader_id:profile.id,book_id:b.id,amount:b.price,author_share:s.author,platform_fee:s.platform,status:"COMPLETED"}).select("id").single();if(order.error){setNotice(order.error.message);return}await addLibrary(b);setNotice("Purchase recorded and added to your library.")}}
 async function addLibrary(b:Book){if(!profile||!supabaseConfigured){setReader({book:b,page:1,preview:false});return}const q=await supabase.from("library").upsert({user_id:profile.id,book_id:b.id,last_page:1,progress:0,completed:false},{onConflict:"user_id,book_id"});if(q.error){setNotice(q.error.message);return}await load();setReader({book:b,page:1,preview:false})}
 return <div className="app"><Header profile={profile} view={view} setView={setView} onAuth={()=>setAuth(true)} onOut={async()=>{await supabase.auth.signOut();setProfile(null)}} search={search} setSearch={setSearch}/>
 {notice&&<div className="notice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
 {selected?<Detail book={selected} back={()=>setSelected(null)} preview={()=>setReader({book:selected,page:1,preview:!selected.is_free})} buy={()=>buy(selected)}/>:
 reader?<Reader book={reader.book} page={reader.page} preview={reader.preview} close={()=>setReader(null)} pageSet={p=>setReader({...reader,page:p})}/>:
 view==="discover"?<Discover books={filtered} loading={loading} open={setSelected} sell={()=>{if(!profile)setAuth(true);else if(profile.role==="AUTHOR")setPublish(true);else setNotice("Only Author accounts can publish.")}}/>:
 view==="library"?<Library items={library} open={setSelected}/>:
 view==="author"?<Author profile={profile} books={books.filter(b=>b.author_id===profile?.id)} publish={()=>setPublish(true)}/>:
 <ProfilePage profile={profile}/>}
 {auth&&<AuthModal close={()=>setAuth(false)} done={p=>{setProfile(p);setAuth(false)}}/>}{publish&&<Publish profile={profile} close={()=>setPublish(false)} done={()=>{setPublish(false);load()}} error={setNotice}/>}</div>
}

function Header(p:any){return <><header className="header"><button className="brand" onClick={()=>p.setView("discover")}>◈ BookSphere</button><nav><button className={p.view==="discover"?"active":""} onClick={()=>p.setView("discover")}>Discover</button><button className={p.view==="library"?"active":""} onClick={()=>p.setView("library")}>My Library</button>{p.profile?.role==="AUTHOR"&&<button className={p.view==="author"?"active":""} onClick={()=>p.setView("author")}>Author Studio</button>}</nav><div className="headerRight"><input value={p.search} onChange={e=>p.setSearch(e.target.value)} placeholder="Search books..."/>{p.profile?<button className="avatar" onClick={()=>p.setView("profile")}>{(p.profile.name||"R")[0]}</button>:<button className="darkButton" onClick={p.onAuth}>Sign in</button>}</div></header><div className="mobileNav"><button className={p.view==="discover"?"active":""} onClick={()=>p.setView("discover")}>⌂<span>Discover</span></button><button className={p.view==="library"?"active":""} onClick={()=>p.setView("library")}>▤<span>My Library</span></button><button className={p.view==="author"?"active":""} onClick={()=>p.setView("author")}>✎<span>Studio</span></button><button className={p.view==="profile"?"active":""} onClick={()=>p.setView("profile")}>◯<span>Profile</span></button></div></>}

function Discover(p:any){return <main className="page"><section className="hero"><div><span className="eyebrow">FAIR MARKETPLACE STANDARD</span><h1>A fair platform for authors and readers.</h1><p>Authors set their own prices. Readers can try the opening pages before buying. <b>70% goes directly to the author.</b></p><div className="actions"><button className="lightButton" onClick={()=>p.books[0]&&p.open(p.books[0])}>Start Reading →</button><button className="outlineButton" onClick={p.sell}>Start Selling</button></div></div><div className="heroStats"><b>70/30</b><span>author / platform</span><b>2–3</b><span>free preview pages</span></div></section><div className="sectionHead"><div><span className="eyebrow">HAND-CURATED</span><h2>Discover your next book</h2></div><span>{p.books.length} books</span></div>{p.loading?<div className="empty">Loading catalog...</div>:<div className="bookGrid">{p.books.map((b:Book,i:number)=><Card key={b.id} book={b} i={i} open={p.open}/>)}</div>}<section className="split"><div><span className="eyebrow">FOR AUTHORS</span><h2>Keep control of your work.</h2><p>Upload your manuscript, set your price, and see the exact revenue split.</p><button className="darkButton" onClick={p.sell}>Publish a manuscript</button></div><div className="metric"><b>70%</b><span>of every paid sale goes to the author</span></div></section></main>}

function Card({book,i,open}:any){return <article className="bookCard" onClick={()=>open(book)}><img src={cover(book,i)}/><div className="bookInfo"><span className="pill">{book.is_free?"FREE":"₹"+Number(book.price).toFixed(0)}</span><h3>{book.title}</h3><p>by {book.author_name}</p><div className="meta"><span>★ {Number(book.rating).toFixed(1)}</span><span>{book.genre}</span></div></div></article>}

function Detail(p:any){const s=revenueSplit(p.book.price);return <main className="detail"><button className="back" onClick={p.back}>← Back to Discover</button><div className="detailGrid"><img className="detailCover" src={cover(p.book)}/><div><span className="pill">{p.book.is_free?"FREE EDITION":"₹"+p.book.price}</span><h1>{p.book.title}</h1><h3>by {p.book.author_name}</h3><p className="lead">{p.book.description}</p><div className="detailMeta"><span>★ {p.book.rating}</span><span>{p.book.genre}</span><span>{p.book.total_pages} pages</span></div><div className="bookActions"><button className="darkButton" onClick={p.preview}>{p.book.is_free?"Read full book":"Read free preview"}</button>{!p.book.is_free&&<button className="outlineDark" onClick={p.buy}>Buy for ₹{p.book.price}</button>}</div>{!p.book.is_free&&<div className="revenue"><strong>Transparent revenue</strong><span>Author <b>₹{s.author.toFixed(2)}</b> · 70%</span><span>BookSphere <b>₹{s.platform.toFixed(2)}</b> · 30%</span></div>}</div></div></main>}

function Reader(p:any){const canvas=useRef<HTMLCanvasElement>(null),[source,setSource]=useState<Blob|null>(null),[error,setError]=useState("");const allowed=p.preview?Math.min(p.book.preview_pages,p.book.total_pages):p.book.total_pages;
 useEffect(()=>{let live=true;(async()=>{try{let b:Blob|null=null;if(p.book.preview_path&&supabaseConfigured){const x=await supabase.storage.from("previews").download(p.book.preview_path);b=x.data}if(b&&live)setSource(b);else if(p.book.manuscript_path&&supabaseConfigured&&!p.preview){const x=await supabase.storage.from("manuscripts").download(p.book.manuscript_path);if(live)setSource(x.data)}}catch(e){if(live)setError(e instanceof Error?e.message:"Unable to open manuscript")}})();return()=>{live=false}},[p.book.id,p.preview]);
 useEffect(()=>{if(canvas.current&&source)renderPdfPage(source,p.page,canvas.current).catch(e=>setError(e.message))},[source,p.page]);
 return <div className="reader"><div className="readerTop"><button onClick={p.close}>×</button><div><b>{p.book.title}</b><small>{p.preview?"Free preview · first "+allowed+" pages":"Full edition"}</small></div><span>Page {p.page} / {allowed}</span></div><div className="readerBody">{source?<canvas ref={canvas}/>:<div className="paper"><span className="chapter">BOOKSPHERE READING ROOM</span><h1>{p.book.title}</h1><h2>Page {p.page}</h2><p>{p.page===1?p.book.description:"Your manuscript is ready here once the PDF is connected."}</p><p>Page 1 is always included in a generated preview.</p></div>}{error&&<div className="readerError">{error}</div>}</div><div className="readerBottom"><button onClick={()=>p.pageSet(p.page-1)} disabled={p.page===1}>←</button><div className="progress"><span style={{width:(p.page/allowed*100)+"%"}}/></div><button onClick={()=>p.pageSet(p.page+1)} disabled={p.page>=allowed}>→</button></div></div>}

function Library(p:any){return <main className="page"><div className="streak"><b>🔥 18-Day Streak</b><span>Keep reading — every page counts.</span></div><div className="sectionHead"><h2>My Library</h2><span>{p.items.length} volumes</span></div>{p.items.length?<div className="bookGrid">{p.items.map((x:LibraryEntry,i:number)=><Card key={x.id} book={x.book} i={i} open={p.open}/>)}</div>:<div className="empty">Your library is empty.</div>}</main>}

function Author(p:any){const gross=p.books.reduce((s:number,b:Book)=>s+Number(b.price)*b.copies_sold,0);return <main className="page"><div className="sectionHead"><h1>Author Studio</h1><button className="darkButton" onClick={p.publish}>+ Publish manuscript</button></div><div className="stats"><div><span>Gross sales</span><b>₹{gross.toFixed(2)}</b></div><div><span>Your net · 70%</span><b>₹{(gross*AUTHOR_SHARE).toFixed(2)}</b></div><div><span>Platform · 30%</span><b>₹{(gross*PLATFORM_SHARE).toFixed(2)}</b></div></div><h2>Your works</h2><div className="bookGrid">{p.books.map((b:Book,i:number)=><Card key={b.id} book={b} i={i} open={()=>{}}/>)}</div></main>}

function ProfilePage({profile}:any){return <main className="page">{profile?<><div className="profileHead"><div className="bigAvatar">{(profile.name||"R")[0]}</div><div><span className="eyebrow">{profile.role}</span><h1>{profile.name}</h1><p>{profile.bio||"A BookSphere reader and book lover."}</p></div></div><div className="split"><div><h2>Reading philosophy</h2><p>Try the opening pages and support independent authors directly.</p></div><div><h2>Fair marketplace</h2><p>70% of every paid book goes to its author.</p></div></div></>:<div className="empty">Sign in to view your profile.</div>}</main>}

function AuthModal(p:any){const [mode,setMode]=useState<"signin"|"signup">("signin"),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[role,setRole]=useState<Role>("READER"),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function submit(){setBusy(true);setError("");try{if(!supabaseConfigured)throw new Error("Connect Supabase using .env.local first.");const r=mode==="signup"?await supabase.auth.signUp({email,password,options:{data:{name,role}}}):await supabase.auth.signInWithPassword({email,password});if(r.error)throw r.error;if(!r.data.user)throw new Error("No authenticated user returned.");if(mode==="signup"&&!r.data.session){setError("Account created. Please verify your email, then sign in.");return}let q=await supabase.from("profiles").select("*").eq("id",r.data.user.id).single();if(!q.data&&mode==="signup"){await new Promise(x=>setTimeout(x,500));q=await supabase.from("profiles").select("*").eq("id",r.data.user.id).single()}if(!q.data)throw new Error("Profile was not created. Run the supplied Supabase SQL migration.");p.done(q.data as Profile)}catch(e){setError(e instanceof Error?e.message:"Authentication failed")}finally{setBusy(false)}}
 return <div className="modalBack"><div className="modal"><button className="modalClose" onClick={p.close}>×</button><span className="eyebrow">BOOKSPHERE ACCOUNT</span><h2>{mode==="signin"?"Welcome back":"Create your account"}</h2>{mode==="signup"&&<input placeholder="Full name" value={name} onChange={e=>setName(e.target.value)}/>}<input placeholder="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/>{mode==="signup"&&<div className="roleToggle"><button className={role==="READER"?"selected":""} onClick={()=>setRole("READER")}>Reader</button><button className={role==="AUTHOR"?"selected":""} onClick={()=>setRole("AUTHOR")}>Author</button></div>}{error&&<p className="error">{error}</p>}<button className="darkButton full" disabled={busy} onClick={submit}>{busy?"Please wait...":mode==="signin"?"Sign in":"Create account"}</button><button className="textButton" onClick={()=>setMode(mode==="signin"?"signup":"signin")}>{mode==="signin"?"Need an account? Sign up":"Already have an account? Sign in"}</button></div></div>}

function Publish(p:any){const [title,setTitle]=useState(""),[author,setAuthor]=useState(p.profile?.name||""),[description,setDescription]=useState(""),[genre,setGenre]=useState("Literary Fiction"),[price,setPrice]=useState("199"),[free,setFree]=useState(false),[previewPages,setPreviewPages]=useState("3"),[pdf,setPdf]=useState<File|null>(null),[coverFile,setCoverFile]=useState<File|null>(null),[busy,setBusy]=useState(false);
 async function go(){if(!p.profile){p.error("Sign in as Author first.");return}if(!supabaseConfigured){p.error("Connect Supabase before publishing.");return}if(!pdf){p.error("Select a PDF manuscript.");return}setBusy(true);try{const pages=await getPdfPageCount(pdf),pc=Math.max(1,Math.min(Number(previewPages)||3,pages)),id=crypto.randomUUID(),base=p.profile.id+"/"+id;let coverPath=null;if(coverFile){coverPath=base+"/cover-"+coverFile.name.replace(/[^a-zA-Z0-9._-]/g,"_");const x=await supabase.storage.from("covers").upload(coverPath,coverFile,{upsert:true});if(x.error)throw x.error}const m=base+"/manuscript.pdf",pr=base+"/preview.pdf";let x=await supabase.storage.from("manuscripts").upload(m,pdf,{upsert:true});if(x.error)throw x.error;const preview=await createPreviewPdf(pdf,pc);x=await supabase.storage.from("previews").upload(pr,preview,{upsert:true});if(x.error)throw x.error;const q=await supabase.from("books").insert({id,author_id:p.profile.id,title,author_name:author||p.profile.name||"Independent Author",description,genre,language:"English",price:free?0:Number(price),is_free:free,total_pages:pages,preview_pages:pc,cover_path:coverPath,manuscript_path:m,preview_path:pr,status:"PUBLISHED"});if(q.error)throw q.error;p.done()}catch(e){p.error(e instanceof Error?e.message:"Publication failed")}finally{setBusy(false)}}
 return <div className="modalBack"><div className="modal wide"><button className="modalClose" onClick={p.close}>×</button><span className="eyebrow">AUTHOR STUDIO</span><h2>Publish a manuscript</h2><p className="muted">The preview is a real PDF containing pages 1 through your selected limit.</p><input placeholder="Book title" value={title} onChange={e=>setTitle(e.target.value)}/><input placeholder="Author / pen name" value={author} onChange={e=>setAuthor(e.target.value)}/><textarea placeholder="Description" value={description} onChange={e=>setDescription(e.target.value)}/><div className="two"><select value={genre} onChange={e=>setGenre(e.target.value)}><option>Literary Fiction</option><option>Science Fiction</option><option>Fantasy</option><option>Romance</option><option>Short Stories</option><option>Non-fiction</option></select><input type="number" min="0" value={price} onChange={e=>setPrice(e.target.value)} disabled={free}/></div><label className="check"><input type="checkbox" checked={free} onChange={e=>setFree(e.target.checked)}/> Free book</label><label>Preview pages<input type="number" min="1" max="10" value={previewPages} onChange={e=>setPreviewPages(e.target.value)}/></label><label>Cover image<input type="file" accept="image/*" onChange={e=>setCoverFile(e.target.files?.[0]||null)}/></label><label>Manuscript PDF<input type="file" accept="application/pdf" onChange={e=>setPdf(e.target.files?.[0]||null)}/></label><div className="revenue"><b>70% author · 30% BookSphere</b>{!free&&<span>₹{Number(price||0).toFixed(2)} → ₹{revenueSplit(Number(price||0)).author.toFixed(2)} to author</span>}</div><button className="darkButton full" disabled={busy} onClick={go}>{busy?"Publishing...":"Publish book"}</button></div></div>}
